services:
  rag-django:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - VECTOR_DB_TYPE=faiss
      - DJANGO_SETTINGS_MODULE=django_app.settings
      - DEBUG=False
    volumes:
      - ./documents:/app/documents
      - ./indexes:/app/indexes
      - ./logs:/app/logs
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - rag-migrate

  rag-migrate:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DJANGO_SETTINGS_MODULE=django_app.settings
    volumes:
      - ./documents:/app/documents
      - ./indexes:/app/indexes
      - ./logs:/app/logs
    command: ["python", "manage.py", "migrate"]

volumes:
  documents:
  indexes:
  logs:
  media:
  staticfiles:
