# Generated by Django 5.2.4 on 2025-07-24 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE rag_app_document ADD COLUMN chunk_count_new INTEGER DEFAULT 0;",
            reverse_sql="ALTER TABLE rag_app_document DROP COLUMN chunk_count_new;"
        ),
        migrations.RunSQL(
            "UPDATE rag_app_document SET chunk_count_new = COALESCE(chunk_count, 0);",
            reverse_sql="SELECT 1;"
        ),
        migrations.RunSQL(
            "ALTER TABLE rag_app_document DROP COLUMN chunk_count;",
            reverse_sql="ALTER TABLE rag_app_document ADD COLUMN chunk_count INTEGER NOT NULL;"
        ),
        migrations.RunSQL(
            "ALTER TABLE rag_app_document RENAME COLUMN chunk_count_new TO chunk_count;",
            reverse_sql="ALTER TABLE rag_app_document RENAME COLUMN chunk_count TO chunk_count_new;"
        ),
        migrations.RunSQL(
            "ALTER TABLE rag_app_document ADD COLUMN processed_new BOOLEAN DEFAULT 0;",
            reverse_sql="ALTER TABLE rag_app_document DROP COLUMN processed_new;"
        ),
        migrations.RunSQL(
            "UPDATE rag_app_document SET processed_new = COALESCE(processed, 0);",
            reverse_sql="SELECT 1;"
        ),
        migrations.RunSQL(
            "ALTER TABLE rag_app_document DROP COLUMN processed;",
            reverse_sql="ALTER TABLE rag_app_document ADD COLUMN processed BOOLEAN NOT NULL;"
        ),
        migrations.RunSQL(
            "ALTER TABLE rag_app_document RENAME COLUMN processed_new TO processed;",
            reverse_sql="ALTER TABLE rag_app_document RENAME COLUMN processed TO processed_new;"
        ),
    ]
