# Generated by Django 5.2.4 on 2025-07-26 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0002_add_chunk_count_default'),
        ('rag_app', '0002_auto_20250724_2328'),
    ]

    operations = [
    ]
